// Function for Image Paths
export function getImage() {
    return {
        avatar: "/images/avatar-1.jpg",
        css3: "/images/css3.svg",
        favicon: "/images/favicon.svg",
        figma: "/images/figma.svg",
        heroBanner: "/images/hero-banner.png",
        javascript: "/images/javascript.svg",
        logo: "/images/logo.svg",
        powerbi: "/images/powerbi.svg",
        mongodb: "/images/mongodb.svg",
        people1: "/images/people-1.jpg",
        people2: "/images/people-2.jpg",
        people3: "/images/people-3.jpg",
        people4: "/images/people-4.jpg",
        people5: "/images/people-5.jpg",
        people6: "/images/people-6.jpg",
        project1: "/images/project-1.jpg",
        project2: "/images/project-2.jpg",
        project3: "/images/project-3.jpg",
        project4: "/images/project-4.jpg",
        project5: "/images/project-5.jpg",
        project6: "/images/project-6.jpg",
        react: "/images/react.svg",
        tailwindcss: "/images/tailwindcss.svg",
        python: "/images/python.svg",
        java: "/images/java.svg",
        mysql: "/images/mysql.svg",
        postgres: "/images/postgres.svg",
        firebase: "/images/firebase.svg",
        postman: "/images/postman.svg",
        spring: "/images/spring.svg",
        springboot: "/images/springboot.svg",
        aws: "/images/aws.svg",
        nextjs: "/images/next.svg",
        tensorflow: "/images/tensorflow.svg",
        expo: "/images/expo.svg",
        git: "/images/git.svg",
    };
}

export default getImage;